# Generated by Django 5.1.5 on 2025-01-31 10:20

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('tgl_dibuat', models.DateField()),
                ('tgl_dipublish', models.DateField(auto_now_add=True)),
                ('konten', markdownx.models.MarkdownxField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
